@startuml case diagram
skinparam actorStyle awesome
left to right direction
actor "User" as fc
actor "Admin" as ad
rectangle "Co-working space booking" {
  usecase "Register" as UC1
  usecase "Login" as UC2
  usecase "Logout" as UC3
  usecase "Booking" as UC4
  usecase "Update booking details" as UC6
  usecase "Update co-working space details" as UC7
}
UC1 <. UC2 : include
UC2 <. UC4 : include
UC2 <. UC6 : include
UC2 <. UC7 : include
UC2 <. UC3 : include
ad -up-> UC3
ad -up-> UC4
ad -up-> UC1
fc --> UC1
fc --> UC2
fc --> UC3
fc --> UC4
ad -up-> UC6
fc --> UC6
ad -up-> UC7
ad -up-> UC2
@enduml

